# 회원가입
POST http://localhost:8081/auth/signup
Content-Type: application/json

{
  "email": "user@example.com",
  "name": "John Doe",
  "password": "password123"
}

###

# 로그인
POST http://localhost:8081/auth/signin
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}
