// ActionType.js

export const CREATE_NEW_MESSAGE = "CREATE_NEW_MESSAGE";
export const GET_ALL_MESSAGE = "GET_ALL_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const UPLOAD_FILE_MESSAGE = "UPLOAD_FILE_MESSAGE";
